# Generated by Django 4.2.8 on 2023-12-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RareUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=155)),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('state_name', models.CharField(max_length=20)),
                ('county_name', models.CharField(max_length=20)),
                ('is_contractor', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=20)),
                ('county_name', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField()),
                ('description', models.TextField()),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_accepted', to='Buildoapi.rareuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders_posted', to='Buildoapi.rareuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildoapi.status')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_contractor', to='Buildoapi.rareuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders_customer', to='Buildoapi.rareuser')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildoapi.rating')),
            ],
        ),
    ]
