# Generated by Django 4.2.8 on 2024-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='workorder',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='work_order_images/'),
        ),
    ]
